### ISSUE TITLE
README mentions  2 ways of how to specify a RELEASE in the changelog

### ISSUE THREAD

**Issue by julianrubisch** [yarmiganosca/structured_changelog#6]
`== RELEASE` 

vs

`## RELEASE`

**Comment by yarmiganosca** [comment]
Thanks for reporting this! It's an artifact of converting the readme from markdown to asciidoc. But you should use the ## syntax, because regardless of my markup language preferences, most people seem to prefer markdown, so the gem assumes you'll use a markdown changelog file.
Also, if you use the git commit messages to record release lines, the gem will always generate correctly formatted release sections for you, so that might be an option for you as well.
I'll make sure to fix the readme tonight

**Comment by yarmiganosca** [comment]
Fixed by https://github.com/yarmiganosca/structured_changelog/commit/2039de66aee10facac863343dbc504d26a21fb46
